### ISSUE TITLE
Improve result item design

### ISSUE THREAD

**Issue by kunzstef** [EEXCESS/gdocs-plugin#11]
improve result item design:
- display longer titles
- extend green hover background color by adding padding left of  the displayed image
- style items without image differently  to save space
- remove empty space above  “get recommendations”-button -> redundant, see #6 

review:
-  The design of the result items needs to be improved:
  - The titles are too short, only displaying 3 or 4 words before being cut off.  This makes it very hard to know what the article is, thus making this tool rather unhelpful.  If you need to open 5 or 10 articles just because you can’t read the title, it’s not very helpful.
  - The hover info does help with this - but still, the title is the most important info here and should be displayed better.
  - The green hover background color should extend farther horizontally.  It looks strange ending exactly at the edge of the image.
  - Most result items don’t have images.  Perhaps style these differently so they don’t have a useless grey square taking up valuable space.
  - There is an empty space between the results and the line above “Get recommendations” button.  This doesn’t seems to serve any purpose - please remove.  A screenshot:

**Comment by chseifert** [comment]
could be a separate image/other result view, as in the chrome extension https://chrome.google.com/webstore/detail/eexcessdev/oibioeefnhaadmajhagebgfdmgjjdgbe (note, that this is the development version which currently has some server issues)

This then overlaps with issue #5

**Comment by chseifert** [comment]
Do you get a default thumbnail image? There should be different ones for audio, video, text, 3d and unknown. Are they returned using the dev server? If not an issue should be created.

**Comment by kunzstef** [comment]
Switch to new API/dev server was not completed yet. Default image gets fetched now if preview is not available or can't be loaded.

**Comment by chseifert** [comment]
Some more improvements:
- [ ] include author names for the type "scholarly"
- [x] include year for the type "scholarly"
- [x] convert upper case titles into camel case, e.g. this one https://www.mendeley.com/catalog/evolution-lovelace-early-editions-samuel-richardsons-clarissa/ should become "The evolution of " (etc..)
- [x] mouse over only works sometimes (tested in OS X/Safari and OS X/Chrome)
- [x] for the type "all and cultural" add the information about the type (audio/video etc), since this can't be inferred from the preview images, if they are not the default images)
- [ ] replace \" in title/description with " -> won't do

**Comment by kunzstef** [comment]
@chseifert is this issue still present and should author names be included for the type "scholarly"?

**Comment by chseifert** [comment]
Display author names in the mouse-over popup but not directly with the results. Rationale:
- Author names may be long text (Author 1 and Author 2... Author X), and this would need more sophisticated methods to find a good abbreviation. 
- The title is sometimes already very long.
