### ISSUE TITLE
SyntaxError: String contains control character

### ISSUE THREAD

**Issue by schloett** [EEXCESS/gdocs-plugin#22]
Got the above mentioned error message after authorizing the app - no sidepane appears :(
(see attached screenshot)
![gdocs_bug](https://cloud.githubusercontent.com/assets/4618499/9200561/b54c4cf6-4048-11e5-8c49-ac1b80839ba3.PNG)

**Comment by chseifert** [comment]
Ludwig has the same problem. @schloett could you give more information on your OS/browser version. It seems to be related to windows (and maybe only reproducible there)

**Comment by schloett** [comment]
The error occurs on OS X (Yosemite) and Win 7. Chrome version on both systems is 44.0.2403.155.

I got the error after I accepted a request for authorizing the add-on, now get it every time I try to start the add-on. I assumed that maybe it is a problem with the authorization, so I checked the apps connected to my google account, which listed E-Explorer twice (one authorized in June, one authorized in July). I deleted them both, but without any change. But maybe something bad happened during the authorization procedure, since the two entries mentioned above had June and July as authorization dates, while there was none with August.

**Comment by chseifert** [comment]
no problems with OS X / (Yosemite), Chrome Version 44.0.2403.155 (64-bit)
Same apps connected to my account: E-Explorer twice (one authorized in June, one authorized in July). But I was not asked to authorise the add-on (as I already have had it authorised from the beginning).
But it's still odd, since other testers don't report problems (but I don't know their settings). Could it be a "first authorization try with Windows" and "wrong character encoding of something" problem?

**Comment by kunzstef** [comment]
I could not reproduce this issue. Seams to be an authorization problem. Tested authorization/add-on with Win7 32-bit and Chrome 44.0.2403.157 and everything works fine.

**Comment by kunzstef** [comment]
Was now able to reproduce this issue. Occurs when add-on is loaded with German language setting in firefox.
